In [1]:
from __future__ import print_function
from IPython.display import display, HTML
import os
import sys
import csv
import time
import statistics
import numpy as np
import string
import re
import pandas as pd
import lvExtractor as le
import jieba.posseg as pseg
import thulac

## Emotional Ontology Lexicon

In [8]:
eoLexiconDf = pd.read_csv("EOLexicon.csv", encoding='UTF-8')
#display(eoLexiconDf[eoLexiconDf.词语 == "脏乱"].情感分类[0][0])
#print(eoLexiconDf[eoLexiconDf.词语 == "脏乱"].shape[0])
print(eoLexiconDf["情感分类"].iloc[0])

NN


In [3]:
print(le.getLexiconVector("我爱北京天安门"))
print(le.getLexiconVector("我爱北京天安门").shape)

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\richi\AppData\Local\Temp\jieba.cache
Loading model cost 0.807 seconds.
Prefix dict has been built succesfully.


[[[0.]
  [0.]
  [1.]
  [1.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[1.]
  [0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]
  [1.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [1.]
  [1.]
  [0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [1.]
  [1.]
  [0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]]]
(4, 10, 1)


In [20]:
display(eoLexiconDf)

词语   词性种类  词义数  词义序号 情感分类  强度  极性 辅助情感分类  强度.1  极性.1 Unnamed: 10  \
0         脏乱    adj  1.0   1.0   NN   7   2    NaN   NaN   NaN         NaN   
1         糟报    adj  1.0   1.0   NN   5   2    NaN   NaN   NaN         NaN   
2         早衰    adj  1.0   1.0   NE   5   2    NaN   NaN   NaN         NaN   
3         责备   verb  1.0   1.0   NN   5   2    NaN   NaN   NaN         NaN   
4         贼眼   noun  1.0   1.0   NN   5   2    NaN   NaN   NaN         NaN   
5         战祸   noun  1.0   1.0   ND   5   2     NC   5.0   2.0         NaN   
6         招灾    adj  1.0   1.0   NN   5   2    NaN   NaN   NaN         NaN   
7         折辱   noun  1.0   1.0   NE   5   2     NN   5.0   2.0         NaN   
8        中山狼   noun  1.0   1.0   NN   5   2    NaN   NaN   NaN         NaN   
9         清峻    adj  1.0   1.0   PH   5   0    NaN   NaN   NaN         NaN   
10        清莹    adj  1.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
11        轻倩    adj  1.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
12        晴丽    adj  1.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
13        求索    adj  1.0   1.0   PH   3   1    NaN   NaN   NaN         NaN   
14        热潮   noun  1.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
15        仁政   noun  1.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
16        荣名   noun  1.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
17        柔腻    adj  1.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
18        瑞雪   noun  1.0   1.0   PA   5   1    NaN   NaN   NaN         NaN   
19        擅名   noun  1.0   1.0   PD   7   1    NaN   NaN   NaN         NaN   
20        神采    adj  1.0   1.0   PA   5   1     PH   1.0   1.0         NaN   
21        省便    adj  1.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
22        盛开   verb  1.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
23        盛誉   noun  1.0   1.0   PH   5   1     PA   1.0   1.0         NaN   
24        诗仙   noun  1.0   1.0   PH   7   1    NaN   NaN   NaN         NaN   
25        爽脆    adj  1.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
26        素洁    adj  1.0   1.0   PH   3   1    NaN   NaN   NaN         NaN   
27        诪张   verb  1.0   1.0   NN   5   2    NaN   NaN   NaN         NaN   
28        株连   verb  1.0   1.0   NN   7   2    NaN   NaN   NaN         NaN   
29        坠毁   verb  1.0   1.0   NB   5   2    NaN   NaN   NaN         NaN   
...      ...    ...  ...   ...  ...  ..  ..    ...   ...   ...         ...   
27436    阳关道   noun  1.0   1.0   PA   5   1    NaN   NaN   NaN         NaN   
27437  以文会友　  idiom  1.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
27438   易子析骸  idiom  1.0   1.0   NB   7   2    NaN   NaN   NaN         NaN   
27439   意出望外  idiom  1.0   1.0   PC   5   0    NaN   NaN   NaN         NaN   
27440   溢言虚美  idiom  1.0   1.0   ND   5   2    NaN   NaN   NaN         NaN   
27441   阴差阳错  idiom  1.0   1.0   NN   3   0    NaN   NaN   NaN         NaN   
27442   淫词秽语  idiom  1.0   1.0   ND   7   2    NaN   NaN   NaN         NaN   
27443   银钩铁画  idiom  1.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
27444   引狼拒虎  idiom  1.0   1.0   NN   3   2    NaN   NaN   NaN         NaN   
27445   饮血崩心  idiom  1.0   1.0   NB   9   0    NaN   NaN   NaN         NaN   
27446   饮鸩解渴  idiom  1.0   1.0   NN   5   2    NaN   NaN   NaN         NaN   
27447   应对如响  idiom  1.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
27448   鹰扬虎噬  idiom  1.0   1.0   NN   5   2    NaN   NaN   NaN         NaN   
27449     荧惑   verb  2.0   1.0   NN   7   2    NaN   NaN   NaN         NaN   
27450     硬气    adj  2.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
27451     优容   verb  1.0   1.0   PE   5   1    NaN   NaN   NaN         NaN   
27452     幽闲    adj  2.0   1.0   PH   5   1    NaN   NaN   NaN         NaN   
27453   油嘴花唇  idiom  1.0   1.0   ND   5   2    NaN   NaN   NaN         NaN   
27454     游历   verb  1.0   1.0   PA   3   1    NaN   NaN   NaN         NaN   
27455     友邦   noun  1.0   1.0  

## HowNet

In [4]:
posSentFile = open("sentiment/正面情感词语（中文）.txt", encoding="utf8")
posSentWords = []
hnCount = 0
for line in posSentFile:
    hnCount += 1
    if(hnCount <= 2):
        continue
    posSentWords.append(line)
print("Num Pos Sent Words: " + str(len(posSentWords)))

Num Pos Sent Words: 836


## NTUSD

In [5]:
ntPosFile = open("ntusd-positive.txt", encoding="utf8")
ntPosWords = []
for line in ntPosFile:
    ntPosWords.append(line)
print(len(ntPosWords))

2811


## Test POS tagging

In [3]:
thu1 = thulac.thulac()  #默认模式
text = thu1.cut("我爱北京天安门", text=True)  #进行一句话分词
print(text)
words = pseg.cut("我爱脏乱")
for w in words:
    print('%s %s' % (w.word, w.flag))

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\richi\AppData\Local\Temp\jieba.cache


Model loaded succeed
我_r 爱_v 北京_ns 天安门_ns


Loading model cost 0.918 seconds.
Prefix dict has been built succesfully.


我 r
爱 v
脏乱 n
